version: '3.1'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress_container
    ports:
      - "8001:80"
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example_password
      WORDPRESS_DB_HOST: mysql:3306
    volumes:
      - ./wp_data:/var/www/html
    networks:
      - wordpress_network

  mysql:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: wordpress
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - wordpress_network

networks:
  wordpress_network:
    driver: bridge
